version: 0.2
env:
  #  shell: shell-tag
  variables:
    S3_BUCKET: "standard-rss-feed-simulator-api"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  build:
    commands:
      - echo Installing all requirements
      - npm install
  post_build:
    commands:
    #      - echo Installing test requirements
    #      - pip install -r ./requirements-tests.txt
    #      - echo Running unit testes
    #      - ./bin/tests/unit-coverage-no-report-html.sh
    finally:
      - echo Generating package file
      - aws cloudformation package --template-file sam.yml --s3-bucket $S3_BUCKET --output-template-file packaged.yml
#reports:
#  UnitTestsReports:
#    files:
#      - 'target/unit/clover.xml'
#    file-format: 'CLOVERXML'
artifacts:
  files:
    - sam.yml
    - packaged.yml