AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Lambda deploy'
Resources:
  APIHandler:
    Type: AWS::Lambda::Function
    Properties:
      CodeUri: target
      Handler: lambda.handler
      Environment:
        Variables:
          - DEBUG: true
          - LOG_LEVEL: info
          - APP_ENV: production

